---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hocs-camunda-tools
  labels:
    version: {{.VERSION}}
  annotations:
    downscaler/uptime: {{.UPTIME_PERIOD}}
    #downscaler/uptime: "Mon-Fri 08:00-18:00 Europe/London"
spec:
  replicas: {{.MIN_REPLICAS}}
  selector:
    matchLabels:
      name: hocs-camunda-tools
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hocs-camunda-tools
        role: hocs-camunda-tools
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:v0.0.6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=hocs-camunda-tools.{{.KUBE_NAMESPACE}}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
        resources:
          limits:
            memory: 64Mi
            cpu: 900m
          requests:
            memory: 16Mi
            cpu: 300m

      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy-govuk:v4
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8081'
          - name: LOCATIONS_CSV
            value: '/, /api/'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'TRUE'
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
          - name: ERROR_REDIRECT_CODES
            value: '501 502 503 504'
          - name: ADD_NGINX_HTTP_CFG
            value: 'fastcgi_buffers 16 64k; fastcgi_buffer_size 128k; proxy_buffer_size 128k; proxy_buffers 4 64k; proxy_busy_buffers_size 128k; client_header_buffer_size 8k; large_client_header_buffers 4 128k;'
          - name: ADD_NGINX_SERVER_CFG  
            value: 'rewrite /app/welcome/$ https://$host/app/welcome/default/#/login? permanent;'
          - name: CLIENT_MAX_BODY_SIZE
            value: '52'  
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
        resources:
          limits:
            memory: 32Mi
            cpu: 400m
          requests:
            memory: 4Mi
            cpu: 100m

      - name: hocs-camunda-tools
        image: quay.io/ukhomeofficedigital/hocs-camunda-tools:0.0.4
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        env:
          - name: DB_HOST
            value: 'postgres'
          - name: HOCS_BASICAUTH
            valueFrom:
              secretKeyRef:
                name: ui-casework-creds
                key: plaintext
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-rds
                key: endpoint
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-rds
                key: port
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-rds
                key: db_name
          - name: DB_SCHEMA_NAME
            valueFrom:
              secretKeyRef:
                name: hocs-workflow
                key: rds_schema
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: hocs-workflow
                key: rds_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hocs-workflow
                key: rds_password
        resources:
          limits:
            cpu: 900m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 80Mi
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /certs
            name: certs
            readOnly: true
          - mountPath: /etc/ssl/certs
            name: bundle
            readOnly: true
      
      - name: keycloak-proxy-web
        image: quay.io/keycloak/keycloak-gatekeeper:8.0.2
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            memory: 32Mi
            cpu: 400m
          requests:
            memory: 8Mi
            cpu: 100m
        env:
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: hocs-frontend
                key: encryption_key
        args:
          - --config=/etc/secrets/data.yml
          - --discovery-url=https://sso-dev.notprod.homeoffice.gov.uk/auth/realms/hocs-notprod
          - --openid-provider-proxy=http://hocs-outbound-proxy.{{.KUBE_NAMESPACE}}.svc.cluster.local:31290
          - --listen=127.0.0.1:8081
          - --enable-logging=true
          - --enable-json-logging=true
          - --upstream-url=http://127.0.0.1:8080 # app
          - --upstream-response-header-timeout=60s
          - --upstream-expect-continue-timeout=60s
          - --upstream-keepalive-timeout=60s
          - --server-read-timeout=60s
          - --server-write-timeout=60s
          - --no-redirects=false
          - --resources=uri=/health|white-listed=true
          - --resources=uri=/public/*|white-listed=true
          - --resources=uri=/*
          - --secure-cookie=true
          - --http-only-cookie=true
          - --revocation-url=https://sso-dev.notprod.homeoffice.gov.uk/auth/realms/hocs-notprod/protocol/openid-connect/logout
          - --enable-logout-redirect=true
          - --enable-refresh-tokens=true
          - --encryption-key=$(ENCRYPTION_KEY)
        ports:
          - name: keycloak-http
            containerPort: 8081
        volumeMounts:
          - mountPath: /etc/secrets
            name: frontend-keycloak-secret
            readOnly: true
      
      volumes:
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
        - name: frontend-keycloak-secret
          secret:
            secretName: frontend-keycloak-secret

            